source 'http://rubygems.org'

gem 'rails', '3.1.0.rc5'
gem 'mysql2'
gem 'devise'
gem "oauth-plugin", ">= 0.4.0.pre1"
gem 'haml'
gem 'oauth2'

group :assets do
  gem 'sass-rails', "~> 3.1.0.rc"
  gem 'coffee-rails', "~> 3.1.0.rc"
  gem 'uglifier'
end

gem 'jquery-rails'

group :test do
  gem 'turn', :require => false
end
